name: Deploy AWS
env: 
  NODE_VERSION: '12.x'
on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run lint --if-present
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm test --if-present
  typeCheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run typeCheck --if-present
  build:
    needs: [lint, typeCheck, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - run: npm run build

  deploy:
    needs: build
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Copy files to staging bucket
        run: aws s3 sync ./dist s3://staging.cfe.allencell.org --delete
